// Generated by https://quicktype.io

export interface Result {
    count:    number;
    next:     string;
    previous: null;
    results:  Results[];
}

export interface Results {
    name: string;
    url:  string;
}
